version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./data/rabbitmq/data/:/var/lib/rabbitmq
        - ./data/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: sample-project
      MYSQL_USER: go-user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - '3306:3306'
  redis:
    image: redis
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
networks:
  rabbitmq_go_net:
    driver: bridge
